from constructor import SyntaxTree
import consultant


def main():
    # show menu & read regex
    consultant.show_menu('Convert regex to DFA')
    regex = consultant.read_regex()

    # construct syntax tree
    tree = SyntaxTree()
    tree.build(regex)

    # evaluate functions

    # construct dStates

    # draw DFA

    # read & check input string (optional)
    while True:
        consultant.show_menu(
            'Input string to check, if it can be generated by regex')
        input_string = consultant.read_input_string()


if __name__ == "__main__":
    main()
