def read_option():
    while True:
        try:
            number = input('Input: ')
            number = int(number)
            break
        except ValueError:
            print('Input must be a integer!')
    return int(number)


def init():
    print('REGEX to DFA converter by Jakub Tomkiewicz')
    print('What would you like to do?')
    print('0 - convert REGEX to DFA\n1 - check if input is generated by expression\n2 - see some tests\n3 - exit')

    while True:
        option = read_option()
        if option in range(4):
            break
        print('Insert 0, 1, 2 or 3!')

    if option == 4:
        quit()

    return option
